PygmentsCodeFences = true
baseURL = "http://localhost:1313"
canonifyurls = true
copyright = "© This post is licensed under a Creative Commons Attribution-NonCommercial 4.0 International License，please give source if you wish to quote or reproduce."
disqusShortname = "disqus_shortname"
enableRobotsTXT = true
googleAnalytics = "UA-XXXXXXXX-X"
languageCode = "en"
theme = "hugo-nuo"
title = "Hugo Blog"
[[menu.main]]
identifier = "home"
name = "Home"
url = "/"
weight = 10
[[menu.main]]
identifier = "works"
name = "Works"
url = "https://github.com/laozhu"
weight = 20
[[menu.main]]
identifier = "tags"
name = "Tags"
url = "/tags/"
weight = 30
[params]
author = "Philippe BENOIST"
avatar = "/img/avatar.jpg"
changyan = false
changyanconf = "prod_0908b1cb9a581501753cce1ed074dbe3"
changyanid = "cyt3toRiB"
description = "Hugo is one of the most popular open-source static site generators. With its amazing speed and flexibility, Hugo makes building websites fun again."
email = "name@domain.com"
github = "shantee"
googlesiteverification = "_moDmnnBNVLBN1rzNxyGUGdPHE20YgbmrtzLIbxaWFc"
linkedin = "linkedin_username"
msvalidate = "22596E34341DD1D17D6022C44647E587"
paginate = 10
seotitle = "Hugo Blog (SEO Version)"
subtitle = "~ Keep It Simple & Stupid ~"
twitter = "twitter_username"
wechat = "/img/qrcode.jpg"
weibo = "weibo_username"
